PlayerGym_EventScript_ChooseType::
    lock
    faceplayer
    dynmultichoice 0, 0, FALSE, 5, 0, DYN_MULTICHOICE_CB_DEBUG, gText_Type_Normal, gText_Type_Fighting, gText_Type_Flying, gText_Type_Poison, gText_Type_Ground, gText_Type_Rock, gText_Type_Bug, gText_Type_Ghost, gText_Type_Steel, gText_Type_Fire, gText_Type_Water, gText_Type_Grass, gText_Type_Electric, gText_Type_Psychic, gText_Type_Ice, gText_Type_Dragon, gText_Type_Dark, gText_Type_Fairy
    savegymtype VAR_RESULT
PlayerGym_EventScript_Return:
    release
    end


    
